### ISSUE TITLE
Align dhcp-relay with ols-ucentral-client

### ISSUE THREAD

**Issue by mikehansen1970** [Telecominfraproject/ols-ucentral-schema#8]
Schema is wrong for dhcp-relay configuration, as the client and the examples are assuming configuration at the interface level.

Declare dhcp-relay configuration in interface.ipv4.dhcp.yml as this is where it is referenced in the ols-ucentral-client and configuration examples.
Correct placeholders to being only Interface and VLAN-ID, plus any required free-text within the brackets.

**Comment by Cahb** [comment]
Fixed by Mike's (@mikehansen1970) [PR](https://github.com/Telecominfraproject/ols-ucentral-schema/pull/9).

This can be safely closed, if you don't mind, Mike?

P.S. thanks for the issue and the fix!
